spring.application.name=ceramicas-wari-api

# ===============================
# SQL SERVER
# ===============================
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=BD_CeramicasWari;integratedSecurity=true;encrypt=true;trustServerCertificate=true}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Evita consultas automáticas durante la serialización JSON
spring.jpa.open-in-view=false